### ISSUE TITLE
Consider using git tags and/or github releases for your draft checkpoints instead of putting dates in file names

### ISSUE THREAD

**Issue by fiendish** [ga4gh/ga4gh-copyright-policy#2]
Right now you have a document called "04 Dec 20" that was last modified on January 28 and says "4 Dec. 19" inside the document. Those are three very different points in time.

Since you're using a github code repository for this, and the entire purpose of git is to track revision history, why not have one _living_ draft document and then let git do its thing? You can put summaries of updates in a separate document like the repository README. It would make fixing the document easier (for instance, there's a comma missing after foregoing in the last sentence of 2.ii, various inconsistencies in capitalization, you call the Open Source Initiative the Open Software Initiative, etc, and I could just make a github pull request to fix it directly instead of writing a report about what and where).

**Comment by reece** [comment]
Yes, please don't use dated or versioned filenames.

Dated filenames are counterproductive when using git or Google docs (which provides history and named versions).

**Comment by jb-adams** [comment]
Thanks, I've made this change. I'll loop Adrian in on this since he's working on the policy

**Comment by jb-adams** [comment]
@athorogood I overwrote the Sept 2019 draft policy with the Jan 2020 draft, so that there's now only one living version of the document.

**Comment by athorogood** [comment]
Ok agreed. The next release will be the final in force version and will use this approach.
